import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "./common/Header";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "./common/Footer";
import 'animate.css';
import UseContext from "./UseContext/UseContext";
import MainLayout from "./MainLayout/MainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Frank And Oak",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
       <MainLayout>
       <Header/>
     
     {children}
     <Footer/>
       </MainLayout>
      
      
      
       
        </body>
    </html>
  );
}
